In [1]:
import pandas as pd

In [2]:
file_loc = "/Users/yash.dalmia/Downloads/rejected_count_jan_rejected_count_jan.csv"

In [3]:
df = pd.read_csv(file_loc, names=['C_D', 'C_APP_RES', 'Count'], header=0)

In [4]:
df

               C_D                 C_APP_RES  Count
0    1577817000000  UNVERIFIED_NON_LOGGED_IN    509
1    1577817000000                ML_PROCESS    318
2    1577817000000                 DUPLICATE    109
3    1577817000000                         1     41
4    1577817000000        BATCH_PROCESS_PAST     31
..             ...                       ...    ...
331  1580409000000                 OFFENSIVE     86
332  1580409000000                         1     70
333  1580409000000                 PHONE_NUM     30
334  1580409000000                       URL     14
335  1580409000000                     EMAIL      2

[336 rows x 3 columns]

In [5]:
import time

In [6]:
def get_datetime_string_ist(epoch_millis):
#     return time.strftime('%Y-%m-%d %H:%M:%S', time.localtime(int(epoch_millis)/1000))
    return time.strftime('%Y-%m-%d', time.localtime(int(epoch_millis)/1000))

In [7]:
def convert_dataframe_unstack(df):
    index_list = [(row['C_D'], row['C_APP_RES']) for index, row in df.iterrows()]
    index = pd.MultiIndex.from_tuples(index_list)
    series = pd.Series(df['Count'].tolist(), index = index)
    df_converted = series.unstack(level=1)
    return df_converted

In [8]:
df_converted = convert_dataframe_unstack(df)

In [12]:
df_converted.fillna(0, inplace=True)

In [13]:
df_converted

,1,BATCH_PROCESS_PAST,DUPLICATE,EMAIL,LARGE_COMMENT,ML_PROCESS,OFFENSIVE,PHONE_NUM,PURGE_ACTION,UNVERIFIED_NON_LOGGED_IN,URL,WRONG_NAME
1577817000000,41.0,31.0,109.0,1.0,2.0,318.0,24.0,10.0,6.0,509.0,4.0,0.0
1577903400000,79.0,20.0,104.0,2.0,16.0,338.0,41.0,14.0,2.0,310.0,9.0,0.0
1577989800000,97.0,43.0,89.0,6.0,16.0,457.0,59.0,23.0,10.0,360.0,6.0,0.0
1578076200000,53.0,55.0,80.0,1.0,9.0,453.0,5.0,28.0,1.0,338.0,13.0,0.0
1578162600000,110.0,106.0,99.0,3.0,6.0,480.0,46.0,63.0,8.0,335.0,6.0,0.0
1578249000000,112.0,37.0,110.0,1.0,1.0,492.0,57.0,19.0,18.0,486.0,11.0,0.0
1578335400000,52.0,40.0,112.0,1.0,2.0,515.0,40.0,64.0,25.0,514.0,4.0,0.0
1578421800000,53.0,49.0,91.0,2.0,7.0,431.0,40.0,32.0,3.0,451.0,7.0,0.0
1578508200000,66.0,82.0,86.0,2.0,5.0,386.0,49.0,38.0,32.0,402.0,10.0,0.0
1578594600000,73.0,71.0,82.0,5.0,11.0,349.0,19.0,19.0,29.0,364.0,5.0,0.0
1578681000000,76.0,94.0,92.0,129.0,16.0,416.0,27.0,22.0,8.0,418.0,6.0,0.0
1578767400000,78.0,53.0,150.0,38.0,13.0,346.0,28.0,23.0,85.0,309.0,2.0,0.0
1578853800000,74.0,87.0,95.0,54.0,21.0,416.0,65.0,27.0,51.0,320.0,7.0,0.0
1578940200000,62.0,73.0,104.0,7.0,17.0,427.0,61.0,18.0,18.0,396.0,5.0,0.0
1579026600000,67.0,76.0,132.0,11.0,4.0,413.0,15.0,30.0,16.0,388.0,10.0,0.0
1579113000000,81.0,40.0,96.0,16.0,8.0,406.0,44.0,19.0,11.0,365.0,10.0,0.0
1579199400000,46.0,52.0,64.0,1.0,5.0,360.0,53.0,21.0,42.0,364.0,7.0,0.0
1579285800000,66.0,69.0,88.0,20.0,8.0,576.0,45.0,29.0,7.0,400.0,11.0,0.0
1579372200000,50.0,54.0,68.0,0.0,8.0,381.0,92.0,25.0,19.0,347.0,7.0,0.0
1579458600000,40.0,53.0,79.0,7.0,15.0,462.0,129.0,28.0,48.0,355.0,6.0,0.0
1579545000000,53.0,89.0,80.0,5.0,19.0,622.0,91.0,37.0,20.0,335.0,12.0,0.0
1579631400000,53.0,56.0,89.0,1.0,20.0,373.0,37.0,23.0,13.0,394.0,10.0,0.0
1579717800000,71.0,130.0,63.0,3.0,20.0,456.0,34.0,32.0,19.0,345.0,9.0,0.0
1579804200000,35.0,94.0,72.0,3.0,33.0,609.0,54.0,34.0,21.0,352.0,12.0,0.0
1579890600000,53.0,52.0,71.0,2.0,24.0,382.0,46.0,19.0,5.0,366.0,9.0,0.0
1579977000000,69.0,47.0,118.0,1.0,22.0,462.0,52.0,21.0,28.0,687.0,5.0,0.0
1580063400000,47.0,58.0,85.0,1.0,25.0,585.0,73.0,31.0,14.0,391.0,5.0,0.0
1580149800000,63.0,102.0,108.0,3.0,22.0,631.0,94.0,31.0,12.0,389.0,6.0,0.0
1580236200000,44.0,77.0,98.0,2.0,12.0,441.0,89.0,26.0,0.0,361.0,7.0,0.0
1580322600000,69.0,96.0,112.0,0.0,3.0,495.0,105.0,13.0,0.0,393.0,9.0,1.0
1580409000000,70.0,123.0,109.0,2.0,0.0,546.0,86.0,30.0,0.0,421.0,14.0,0.0

In [15]:
df_converted = df_converted.astype('int32')

In [16]:
df_converted['Date'] = df_converted.index
df_converted['Date'] = df_converted['Date'].apply(lambda x: get_datetime_string_ist(x))

In [21]:
df_converted.to_csv('/Users/yash.dalmia/Downloads/converted_df.csv')

In [18]:
# df_converted['total_count'] = df_converted.index

In [19]:
# df_converted

In [ ]:
# df_converted['total_count']

In [20]:
# df_converted['total_count'] = df_converted['total_count'].apply(lambda x: get_total_count_for_c_d(x))

In [ ]:
df_total = pd.read_csv("/Users/yash.dalmia/Downloads/rejected_count_jan_total_count.csv", names = ["C_D", "count"], header=0)

In [ ]:
df_total

In [ ]:
def get_total_count_for_c_d(c_d_value):
    try:
        return (df_total[df_total['C_D'] == int(c_d_value)]['count'][0])
    except Exception as ex:
        print('exception for c_d : {}'.format(c_d_value))