In [1]:
url = "https://commentmoderator.indiatimes.com/mytimes/elasticCommentQuery?sort=desc&appKey=ETBLOG,LIFEH,ETH,MALAY,TOI,FMI,TOIRB,ZT,IEX,BI,MTB,iDiva,ETR,TELGU,QNAZ,ETT,BM,HEALTHB,TAMB,AdAge,IV,HMP,ZW,ETG,itimes,HTFOOD,GTech,ET,TAMIL,PG,TJC,TR,Travel,MYT_COMMENTS_API_KEY,NBTB,MXP,MKYRA,PM,NBTO,EA,ZEX,NPRSS,TIMESB,ETBFSI,NGSBLOG,LUXP,NPRS,QNA,ES,ELE,TFOOD,ETCIO,MTO,BT,MYTIMES,ST,TS,ESB,ETE,TD,NGS,VKB,mdfkfkf,ETHFI,MALB,CRIC,FMF,GIZ,FEMB,TMC,TELB,NBTRB,TOIBLOG,TBNET,MFB,NBTBU,TILC,MB,Test,Gaana,ETHC,ETPB,CMSA,KS,FEMINA,MM,AM,ETA,iDiva2,MALAYGN,TELGUGN,TAMILGN,VKGN,ESGN,MTGN,NBTG,BNETH,ETPRIME,INDIATIMES,MENSXP,NBTGTECH,NTOIRB,STEN,STHN,TECHGIG,TESTMYT,IAG,ETTECH,ESG&filterCommentStatus=APPROVED,REJECTED,UNVERIFIED&sDate=1%2F1%2F2021&eDate=31%2F1%2F2021&from=0&size=0&queryString=_exists_%3AC_T&aggField=A_K&aggSize=100&aggMinDocCount=1"

In [2]:
import requests

In [3]:
json_res = requests.get(url).json()

In [4]:
json_res

{'_shards': {'total': 1, 'failed': 0, 'successful': 1},
 'hits': {'hits': [], 'total': 457663, 'max_score': 0},
 'took': 107,
 'timed_out': False,
 'aggregations': {'2': {'doc_count_error_upper_bound': 0,
   'sum_other_doc_count': 0,
   'buckets': [{'doc_count': 350355, 'key': 'TOI'},
    {'doc_count': 36852, 'key': 'ET'},
    {'doc_count': 23159, 'key': 'NBTO'},
    {'doc_count': 21789, 'key': 'MTO'},
    {'doc_count': 4711, 'key': 'TIMESB'},
    {'doc_count': 3400, 'key': 'MM'},
    {'doc_count': 2618, 'key': 'ES'},
    {'doc_count': 2250, 'key': 'NBTRB'},
    {'doc_count': 1820, 'key': 'BM'},
    {'doc_count': 1610, 'key': 'NBTG'},
    {'doc_count': 1491, 'key': 'ESG'},
    {'doc_count': 1403, 'key': 'IV'},
    {'doc_count': 1123, 'key': 'INDIATIMES'},
    {'doc_count': 1061, 'key': 'GTech'},
    {'doc_count': 775, 'key': 'TELGU'},
    {'doc_count': 550, 'key': 'STEN'},
    {'doc_count': 544, 'key': 'TOIRB'},
    {'doc_count': 404, 'key': 'ETBLOG'},
    {'doc_count': 361, 'key': 'TFOOD'},
    {'doc_count': 282, 'key': 'ETPRIME'},
    {'doc_count': 237, 'key': 'PM'},
    {'doc_count': 222, 'key': 'TAMIL'},
    {'doc_count': 130, 'key': 'AM'},
    {'doc_count': 122, 'key': 'TJC'},
    {'doc_count': 90, 'key': 'iDiva2'},
    {'doc_count': 76, 'key': 'Travel'},
    {'doc_count': 59, 'key': 'MALAY'},
    {'doc_count': 51, 'key': 'FEMINA'},
    {'doc_count': 40, 'key': 'NBTB'},
    {'doc_count': 19, 'key': 'MTB'},
    {'doc_count': 18, 'key': 'STHN'},
    {'doc_count': 16, 'key': 'FMI'},
    {'doc_count': 7, 'key': 'IAG'},
    {'doc_count': 6, 'key': 'MKYRA'},
    {'doc_count': 5, 'key': 'ESB'},
    {'doc_count': 5, 'key': 'PG'},
    {'doc_count': 2, 'key': 'ETTECH'}]}}}

In [12]:
json_res['aggregations']['2']['buckets']

[{'doc_count': 350355, 'key': 'TOI'},
 {'doc_count': 36852, 'key': 'ET'},
 {'doc_count': 23159, 'key': 'NBTO'},
 {'doc_count': 21789, 'key': 'MTO'},
 {'doc_count': 4711, 'key': 'TIMESB'},
 {'doc_count': 3400, 'key': 'MM'},
 {'doc_count': 2618, 'key': 'ES'},
 {'doc_count': 2250, 'key': 'NBTRB'},
 {'doc_count': 1820, 'key': 'BM'},
 {'doc_count': 1610, 'key': 'NBTG'},
 {'doc_count': 1491, 'key': 'ESG'},
 {'doc_count': 1403, 'key': 'IV'},
 {'doc_count': 1123, 'key': 'INDIATIMES'},
 {'doc_count': 1061, 'key': 'GTech'},
 {'doc_count': 775, 'key': 'TELGU'},
 {'doc_count': 550, 'key': 'STEN'},
 {'doc_count': 544, 'key': 'TOIRB'},
 {'doc_count': 404, 'key': 'ETBLOG'},
 {'doc_count': 361, 'key': 'TFOOD'},
 {'doc_count': 282, 'key': 'ETPRIME'},
 {'doc_count': 237, 'key': 'PM'},
 {'doc_count': 222, 'key': 'TAMIL'},
 {'doc_count': 130, 'key': 'AM'},
 {'doc_count': 122, 'key': 'TJC'},
 {'doc_count': 90, 'key': 'iDiva2'},
 {'doc_count': 76, 'key': 'Travel'},
 {'doc_count': 59, 'key': 'MALAY'},
 {'doc_count': 51, 'key': 'FEMINA'},
 {'doc_count': 40, 'key': 'NBTB'},
 {'doc_count': 19, 'key': 'MTB'},
 {'doc_count': 18, 'key': 'STHN'},
 {'doc_count': 16, 'key': 'FMI'},
 {'doc_count': 7, 'key': 'IAG'},
 {'doc_count': 6, 'key': 'MKYRA'},
 {'doc_count': 5, 'key': 'ESB'},
 {'doc_count': 5, 'key': 'PG'},
 {'doc_count': 2, 'key': 'ETTECH'}]

In [14]:
url2 = "https://commentmoderator.indiatimes.com/mytimes/elasticCommentQuery?sort=desc&appKey=ETBLOG,LIFEH,ETH,MALAY,TOI,FMI,TOIRB,ZT,IEX,BI,MTB,iDiva,ETR,TELGU,QNAZ,ETT,BM,HEALTHB,TAMB,AdAge,IV,HMP,ZW,ETG,itimes,HTFOOD,GTech,ET,TAMIL,PG,TJC,TR,Travel,MYT_COMMENTS_API_KEY,NBTB,MXP,MKYRA,PM,NBTO,EA,ZEX,NPRSS,TIMESB,ETBFSI,NGSBLOG,LUXP,NPRS,QNA,ES,ELE,TFOOD,ETCIO,MTO,BT,MYTIMES,ST,TS,ESB,ETE,TD,NGS,VKB,mdfkfkf,ETHFI,MALB,CRIC,FMF,GIZ,FEMB,TMC,TELB,NBTRB,TOIBLOG,TBNET,MFB,NBTBU,TILC,MB,Test,Gaana,ETHC,ETPB,CMSA,KS,FEMINA,MM,AM,ETA,iDiva2,MALAYGN,TELGUGN,TAMILGN,VKGN,ESGN,MTGN,NBTG,BNETH,ETPRIME,INDIATIMES,MENSXP,NBTGTECH,NTOIRB,STEN,STHN,TECHGIG,TESTMYT,IAG,ETTECH,ESG&filterCommentStatus=APPROVED,REJECTED,UNVERIFIED&sDate=1%2F1%2F2021&eDate=31%2F1%2F2021&from=0&size=0&queryString=_exists_%3AC_T&aggField=A_K,C_APP_RES&aggSize=100&aggMinDocCount=1"

In [15]:
json_res_2 = requests.get(url2).json()

In [17]:
json_res_2['aggregations']['2']['buckets']

[{'doc_count': 350355,
  '3': {'doc_count_error_upper_bound': 0,
   'sum_other_doc_count': 0,
   'buckets': [{'doc_count': 16525, 'key': 'ML_PROCESS'},
    {'doc_count': 7295, 'key': 'UNVERIFIED_NON_LOGGED_IN'},
    {'doc_count': 7127, 'key': 'DUPLICATE'},
    {'doc_count': 5539, 'key': 'PURGE_ACTION'},
    {'doc_count': 4597, 'key': 'OFFENSIVE'},
    {'doc_count': 3291, 'key': 'BATCH_PROCESS_PAST'},
    {'doc_count': 3250, 'key': 'PHONE_NUM'},
    {'doc_count': 884, 'key': '1'},
    {'doc_count': 271, 'key': 'URL'},
    {'doc_count': 101, 'key': 'LARGE_COMMENT'},
    {'doc_count': 53, 'key': 'EMAIL'},
    {'doc_count': 6, 'key': 'ED_OFFENSIVE'}]},
  'key': 'TOI'},
 {'doc_count': 36852,
  '3': {'doc_count_error_upper_bound': 0,
   'sum_other_doc_count': 0,
   'buckets': [{'doc_count': 6401, 'key': 'UNVERIFIED_NON_LOGGED_IN'},
    {'doc_count': 3100, 'key': 'DUPLICATE'},
    {'doc_count': 2069, 'key': 'PHONE_NUM'},
    {'doc_count': 1249, 'key': 'BATCH_PROCESS_PAST'},
    {'doc_count': 948, 'key': 'PURGE_ACTION'},
    {'doc_count': 306, 'key': 'URL'},
    {'doc_count': 154, 'key': 'EMAIL'},
    {'doc_count': 22, 'key': 'LARGE_COMMENT'}]},
  'key': 'ET'},
 {'doc_count': 23159,
  '3': {'doc_count_error_upper_bound': 0,
   'sum_other_doc_count': 0,
   'buckets': [{'doc_count': 216, 'key': 'ML_PROCESS'},
    {'doc_count': 181, 'key': '1'},
    {'doc_count': 176, 'key': 'UNVERIFIED_NON_LOGGED_IN'},
    {'doc_count': 84, 'key': 'DUPLICATE'},
    {'doc_count': 61, 'key': 'BATCH_PROCESS_PAST'},
    {'doc_count': 36, 'key': 'LARGE_COMMENT'},
    {'doc_count': 34, 'key': 'PHONE_NUM'},
    {'doc_count': 29, 'key': 'URL'},
    {'doc_count': 6, 'key': 'ED_OFFENSIVE'},
    {'doc_count': 3, 'key': 'OFFENSIVE'},
    {'doc_count': 1, 'key': 'EMAIL'}]},
  'key': 'NBTO'},
 {'doc_count': 21789,
  '3': {'doc_count_error_upper_bound': 0,
   'sum_other_doc_count': 0,
   'buckets': [{'doc_count': 338, 'key': 'UNVERIFIED_NON_LOGGED_IN'},
    {'doc_count': 82, 'key': 'DUPLICATE'},
    {'doc_count': 53, 'key': 'BATCH_PROCESS_PAST'},
    {'doc_count': 21, 'key': '1'},
    {'doc_count': 10, 'key': 'PURGE_ACTION'},
    {'doc_count': 9, 'key': 'LARGE_COMMENT'},
    {'doc_count': 7, 'key': 'PHONE_NUM'},
    {'doc_count': 6, 'key': 'OFFENSIVE'},
    {'doc_count': 5, 'key': 'URL'},
    {'doc_count': 4, 'key': 'ARTICLE_PASTED'}]},
  'key': 'MTO'},
 {'doc_count': 4711,
  '3': {'doc_count_error_upper_bound': 0,
   'sum_other_doc_count': 0,
   'buckets': [{'doc_count': 54, 'key': 'PHONE_NUM'},
    {'doc_count': 44, 'key': 'DUPLICATE'},
    {'doc_count': 12, 'key': 'BATCH_PROCESS_PAST'},
    {'doc_count': 5, 'key': 'LARGE_COMMENT'},
    {'doc_count': 5, 'key': 'PURGE_ACTION'},
    {'doc_count': 4, 'key': 'OFFENSIVE'},
    {'doc_count': 2, 'key': 'URL'},
    {'doc_count': 1, 'key': 'EMAIL'}]},
  'key': 'TIMESB'},
 {'doc_count': 3400,
  '3': {'doc_count_error_upper_bound': 0,
   'sum_other_doc_count': 0,
   'buckets': [{'doc_count': 868, 'key': 'UNVERIFIED_NON_LOGGED_IN'},
    {'doc_count': 32, 'key': 'DUPLICATE'},
    {'doc_count': 27, 'key': 'PHONE_NUM'},
    {'doc_count': 10, 'key': 'OFFENSIVE'},
    {'doc_count': 8, 'key': 'PURGE_ACTION'},
    {'doc_count': 4, 'key': 'BATCH_PROCESS_PAST'},
    {'doc_count': 2, 'key': 'LARGE_COMMENT'},
    {'doc_count': 1, 'key': 'URL'}]},
  'key': 'MM'},
 {'doc_count': 2618,
  '3': {'doc_count_error_upper_bound': 0,
   'sum_other_doc_count': 0,
   'buckets': [{'doc_count': 19, 'key': 'PURGE_ACTION'},
    {'doc_count': 15, 'key': 'UNVERIFIED_NON_LOGGED_IN'},
    {'doc_count': 6, 'key': 'DUPLICATE'},
    {'doc_count': 6, 'key': 'PHONE_NUM'},
    {'doc_count': 5, 'key': 'BATCH_PROCESS_PAST'},
    {'doc_count': 1, 'key': 'ARTICLE_PASTED'},
    {'doc_count': 1, 'key': 'URL'}]},
  'key': 'ES'},
 {'doc_count': 2250,
  '3': {'doc_count_error_upper_bound': 0,
   'sum_other_doc_count': 0,
   'buckets': [{'doc_count': 28, 'key': 'DUPLICATE'},
    {'doc_count': 2, 'key': 'BATCH_PROCESS_PAST'},
    {'doc_count': 2, 'key': 'PHONE_NUM'},
    {'doc_count': 1, 'key': 'EMAIL'}]},
  'key': 'NBTRB'},
 {'doc_count': 1820,
  '3': {'doc_count_error_upper_bound': 0,
   'sum_other_doc_count': 0,
   'buckets': [{'doc_count': 509, 'key': 'UNVERIFIED_NON_LOGGED_IN'},
    {'doc_count': 32, 'key': 'PHONE_NUM'},
    {'doc_count': 19, 'key': 'BATCH_PROCESS_PAST'},
    {'doc_count': 18, 'key': 'DUPLICATE'},
    {'doc_count': 1, 'key': 'LARGE_COMMENT'},
    {'doc_count': 1, 'key': 'PURGE_ACTION'}]},
  'key': 'BM'},
 {'doc_count': 1610,
  '3': {'doc_count_error_upper_bound': 0,
   'sum_other_doc_count': 0,
   'buckets': [{'doc_count': 6, 'key': 'UNVERIFIED_NON_LOGGED_IN'},
    {'doc_count': 2, 'key': 'PHONE_NUM'},
    {'doc_count': 1, 'key': 'PURGE_ACTION'}]},
  'key': 'NBTG'},
 {'doc_count': 1491,
  '3': {'doc_count_error_upper_bound': 0,
   'sum_other_doc_count': 0,
   'buckets': [{'doc_count': 5, 'key': 'UNVERIFIED_NON_LOGGED_IN'},
    {'doc_count': 1, 'key': 'EMAIL'},
    {'doc_count': 1, 'key': 'PURGE_ACTION'}]},
  'key': 'ESG'},
 {'doc_count': 1403,
  '3': {'doc_count_error_upper_bound': 0,
   'sum_other_doc_count': 0,
   'buckets': [{'doc_count': 7, 'key': 'UNVERIFIED_NON_LOGGED_IN'},
    {'doc_count': 5, 'key': 'BATCH_PROCESS_PAST'},
    {'doc_count': 5, 'key': 'ML_PROCESS'},
    {'doc_count': 1, 'key': 'LARGE_COMMENT'}]},
  'key': 'IV'},
 {'doc_count': 1123,
  '3': {'doc_count_error_upper_bound': 0,
   'sum_other_doc_count': 0,
   'buckets': [{'doc_count': 63, 'key': 'URL'},
    {'doc_count': 32, 'key': 'BATCH_PROCESS_PAST'},
    {'doc_count': 26, 'key': 'DUPLICATE'},
    {'doc_count': 26, 'key': 'PHONE_NUM'},
    {'doc_count': 2, 'key': 'EMAIL'}]},
  'key': 'INDIATIMES'},
 {'doc_count': 1061,
  '3': {'doc_count_error_upper_bound': 0,
   'sum_other_doc_count': 0,
   'buckets': [{'doc_count': 145, 'key': 'UNVERIFIED_NON_LOGGED_IN'},
    {'doc_count': 51, 'key': 'PHONE_NUM'},
    {'doc_count': 6, 'key': 'PURGE_ACTION'},
    {'doc_count': 3, 'key': 'BATCH_PROCESS_PAST'},
    {'doc_count': 3, 'key': 'DUPLICATE'},
    {'doc_count': 3, 'key': 'EMAIL'},
    {'doc_count': 2, 'key': 'URL'}]},
  'key': 'GTech'},
 {'doc_count': 775,
  '3': {'doc_count_error_upper_bound': 0,
   'sum_other_doc_count': 0,
   'buckets': [{'doc_count': 21, 'key': 'BATCH_PROCESS_PAST'},
    {'doc_count': 21, 'key': 'PHONE_NUM'},
    {'doc_count': 6, 'key': 'UNVERIFIED_NON_LOGGED_IN'},
    {'doc_count': 3, 'key': 'EMAIL'},
    {'doc_count': 1, 'key': 'DUPLICATE'},
    {'doc_count': 1, 'key': 'URL'}]},
  'key': 'TELGU'},
 {'doc_count': 550,
  '3': {'doc_count_error_upper_bound': 0,
   'sum_other_doc_count': 0,
   'buckets': [{'doc_count': 14, 'key': 'EMAIL'},
    {'doc_count': 2, 'key': 'URL'},
    {'doc_count': 1, 'key': 'PHONE_NUM'}]},
  'key': 'STEN'},
 {'doc_count': 544,
  '3': {'doc_count_error_upper_bound': 0,
   'sum_other_doc_count': 0,
   'buckets': [{'doc_count': 15, 'key': 'DUPLICATE'},
    {'doc_count': 2, 'key': 'PHONE_NUM'},
    {'doc_count': 1, 'key': 'LARGE_COMMENT'},
    {'doc_count': 1, 'key': 'UNVERIFIED_NON_LOGGED_IN'}]},
  'key': 'TOIRB'},
 {'doc_count': 404,
  '3': {'doc_count_error_upper_bound': 0,
   'sum_other_doc_count': 0,
   'buckets': [{'doc_count': 187, 'key': 'PHONE_NUM'},
    {'doc_count': 5, 'key': 'BATCH_PROCESS_PAST'},
    {'doc_count': 5, 'key': 'LARGE_COMMENT'},
    {'doc_count': 3, 'key': 'EMAIL'}]},
  'key': 'ETBLOG'},
 {'doc_count': 361,
  '3': {'doc_count_error_upper_bound': 0,
   'sum_other_doc_count': 0,
   'buckets': [{'doc_count': 21, 'key': 'UNVERIFIED_NON_LOGGED_IN'},
    {'doc_count': 7, 'key': 'URL'},
    {'doc_count': 2, 'key': 'DUPLICATE'},
    {'doc_count': 1, 'key': 'PHONE_NUM'}]},
  'key': 'TFOOD'},
 {'doc_count': 282,
  '3': {'doc_count_error_upper_bound': 0,
   'sum_other_doc_count': 0,
   'buckets': [{'doc_count': 31, 'key': 'UNVERIFIED_NON_LOGGED_IN'},
    {'doc_count': 3, 'key': 'URL'},
    {'doc_count': 1, 'key': 'PHONE_NUM'}]},
  'key': 'ETPRIME'},
 {'doc_count': 237,
  '3': {'doc_count_error_upper_bound': 0,
   'sum_other_doc_count': 0,
   'buckets': [{'doc_count': 54, 'key': 'UNVERIFIED_NON_LOGGED_IN'},
    {'doc_count': 6, 'key': 'PHONE_NUM'},
    {'doc_count': 1, 'key': 'DUPLICATE'},
    {'doc_count': 1, 'key': 'LARGE_COMMENT'},
    {'doc_count': 1, 'key': 'PURGE_ACTION'}]},
  'key': 'PM'},
 {'doc_count': 222,
  '3': {'doc_count_error_upper_bound': 0,
   'sum_other_doc_count': 0,
   'buckets': [{'doc_count': 20, 'key': 'BATCH_PROCESS_PAST'},
    {'doc_count': 3, 'key': 'UNVERIFIED_NON_LOGGED_IN'},
    {'doc_count': 2, 'key': 'URL'},
    {'doc_count': 1, 'key': 'EMAIL'}]},
  'key': 'TAMIL'},
 {'doc_count': 130,
  '3': {'doc_count_error_upper_bound': 0,
   'sum_other_doc_count': 0,
   'buckets': [{'doc_count': 47, 'key': 'UNVERIFIED_NON_LOGGED_IN'},
    {'doc_count': 17, 'key': 'PHONE_NUM'},
    {'doc_count': 1, 'key': 'DUPLICATE'}]},
  'key': 'AM'},
 {'doc_count': 122,
  '3': {'doc_count_error_upper_bound': 0,
   'sum_other_doc_count': 0,
   'buckets': [{'doc_count': 66, 'key': 'UNVERIFIED_NON_LOGGED_IN'},
    {'doc_count': 7, 'key': 'PHONE_NUM'}]},
  'key': 'TJC'},
 {'doc_count': 90,
  '3': {'doc_count_error_upper_bound': 0,
   'sum_other_doc_count': 0,
   'buckets': [{'doc_count': 20, 'key': 'URL'},
    {'doc_count': 3, 'key': 'PHONE_NUM'}]},
  'key': 'iDiva2'},
 {'doc_count': 76,
  '3': {'doc_count_error_upper_bound': 0,
   'sum_other_doc_count': 0,
   'buckets': [{'doc_count': 8, 'key': 'UNVERIFIED_NON_LOGGED_IN'}]},
  'key': 'Travel'},
 {'doc_count': 59,
  '3': {'doc_count_error_upper_bound': 0,
   'sum_other_doc_count': 0,
   'buckets': [{'doc_count': 21, 'key': 'BATCH_PROCESS_PAST'},
    {'doc_count': 6, 'key': 'PHONE_NUM'},
    {'doc_count': 1, 'key': 'URL'}]},
  'key': 'MALAY'},
 {'doc_count': 51,
  '3': {'doc_count_error_upper_bound': 0,
   'sum_other_doc_count': 0,
   'buckets': [{'doc_count': 18, 'key': 'PHONE_NUM'},
    {'doc_count': 5, 'key': 'URL'},
    {'doc_count': 4, 'key': 'BATCH_PROCESS_PAST'}]},
  'key': 'FEMINA'},
 {'doc_count': 40,
  '3': {'doc_count_error_upper_bound': 0,
   'sum_other_doc_count': 0,
   'buckets': []},
  'key': 'NBTB'},
 {'doc_count': 19,
  '3': {'doc_count_error_upper_bound': 0,
   'sum_other_doc_count': 0,
   'buckets': []},
  'key': 'MTB'},
 {'doc_count': 18,
  '3': {'doc_count_error_upper_bound': 0,
   'sum_other_doc_count': 0,
   'buckets': []},
  'key': 'STHN'},
 {'doc_count': 16,
  '3': {'doc_count_error_upper_bound': 0,
   'sum_other_doc_count': 0,
   'buckets': [{'doc_count': 8, 'key': 'UNVERIFIED_NON_LOGGED_IN'},
    {'doc_count': 1, 'key': 'DUPLICATE'}]},
  'key': 'FMI'},
 {'doc_count': 7,
  '3': {'doc_count_error_upper_bound': 0,
   'sum_other_doc_count': 0,
   'buckets': []},
  'key': 'IAG'},
 {'doc_count': 6,
  '3': {'doc_count_error_upper_bound': 0,
   'sum_other_doc_count': 0,
   'buckets': []},
  'key': 'MKYRA'},
 {'doc_count': 5,
  '3': {'doc_count_error_upper_bound': 0,
   'sum_other_doc_count': 0,
   'buckets': []},
  'key': 'ESB'},
 {'doc_count': 5,
  '3': {'doc_count_error_upper_bound': 0,
   'sum_other_doc_count': 0,
   'buckets': [{'doc_count': 4, 'key': 'UNVERIFIED_NON_LOGGED_IN'}]},
  'key': 'PG'},
 {'doc_count': 2,
  '3': {'doc_count_error_upper_bound': 0,
   'sum_other_doc_count': 0,
   'buckets': [{'doc_count': 1, 'key': 'UNVERIFIED_NON_LOGGED_IN'},
    {'doc_count': 1, 'key': 'URL'}]},
  'key': 'ETTECH'}]

In [1]:
import pandas as pd

In [2]:
loc = '/Users/yash.dalmia/Downloads/jan_2021_rejected_count_raw.csv'

In [3]:
df = pd.read_csv(loc)

In [4]:
df

    A_K: Descending     C_APP_RES: Descending  Count
0               TOI                ML_PROCESS  16525
1               TOI  UNVERIFIED_NON_LOGGED_IN   7297
2               TOI                 DUPLICATE   7127
3               TOI              PURGE_ACTION   5544
4               TOI                 OFFENSIVE   4597
..              ...                       ...    ...
111           MALAY                 PHONE_NUM      6
112           MALAY                       URL      1
113          FEMINA                 PHONE_NUM     18
114          FEMINA                       URL      5
115          FEMINA        BATCH_PROCESS_PAST      4

[116 rows x 3 columns]

In [5]:
df.columns = ['A_K', 'C_APPP_RES', 'Count']

In [6]:
df.columns

Index(['A_K', 'C_APPP_RES', 'Count'], dtype='object')

In [7]:
df_new = df.set_index(['A_K', 'C_APPP_RES'])

In [8]:
df_new

                                 Count
A_K    C_APPP_RES
TOI    ML_PROCESS                16525
       UNVERIFIED_NON_LOGGED_IN   7297
       DUPLICATE                  7127
       PURGE_ACTION               5544
       OFFENSIVE                  4597
...                                ...
MALAY  PHONE_NUM                     6
       URL                           1
FEMINA PHONE_NUM                    18
       URL                           5
       BATCH_PROCESS_PAST            4

[116 rows x 1 columns]

In [9]:
df_new_2 = df_new.unstack(level = 1)

In [10]:
df_new_2

            Count                                                           \
C_APPP_RES      1 ARTICLE_PASTED BATCH_PROCESS_PAST DUPLICATE ED_OFFENSIVE
A_K
AM            NaN            NaN                NaN       1.0          NaN
BM            NaN            NaN               19.0      18.0          NaN
ES            NaN            1.0                5.0       6.0          NaN
ET            NaN            NaN             1249.0    3100.0          NaN
ETBLOG        NaN            NaN                5.0       NaN          NaN
ETPRIME       NaN            NaN                NaN       NaN          NaN
FEMINA        NaN            NaN                4.0       NaN          NaN
GTech         NaN            NaN                3.0       3.0          NaN
INDIATIMES    NaN            NaN               32.0      26.0          NaN
MALAY         NaN            NaN               21.0       NaN          NaN
MM            NaN            NaN                4.0      32.0          NaN
MTO          21.0            4.0               53.0      82.0          NaN
NBTO        181.0            NaN               61.0      84.0          6.0
NBTRB         NaN            NaN                2.0      28.0          NaN
PM            NaN            NaN                NaN       1.0          NaN
TELGU         NaN            NaN               21.0       1.0          NaN
TFOOD         NaN            NaN                NaN       2.0          NaN
TIMESB        NaN            NaN               12.0      44.0          NaN
TJC           NaN            NaN                NaN       NaN          NaN
TOI         884.0            NaN             3291.0    7127.0          NaN

                                                                             \
C_APPP_RES  EMAIL LARGE_COMMENT ML_PROCESS OFFENSIVE PHONE_NUM PURGE_ACTION
A_K
AM            NaN           NaN        NaN       NaN      17.0          NaN
BM            NaN           1.0        NaN       NaN      32.0          1.0
ES            NaN           NaN        NaN       NaN       6.0         19.0
ET          154.0          22.0        NaN       NaN    2069.0        948.0
ETBLOG        3.0           5.0        NaN       NaN     187.0          NaN
ETPRIME       NaN           NaN        NaN       NaN       1.0          NaN
FEMINA        NaN           NaN        NaN       NaN      18.0          NaN
GTech         3.0           NaN        NaN       NaN      51.0          6.0
INDIATIMES    2.0           NaN        NaN       NaN      26.0          NaN
MALAY         NaN           NaN        NaN       NaN       6.0          NaN
MM            NaN           2.0        NaN      10.0      27.0          8.0
MTO           NaN           9.0        NaN       6.0       7.0         10.0
NBTO          NaN          36.0      216.0       3.0      34.0          NaN
NBTRB         1.0           NaN        NaN       NaN       2.0          NaN
PM            NaN           1.0        NaN       NaN       6.0          1.0
TELGU         3.0           NaN        NaN       NaN      21.0          NaN
TFOOD         NaN           NaN        NaN       NaN       1.0          NaN
TIMESB        1.0           5.0        NaN       4.0      54.0          5.0
TJC           NaN           NaN        NaN       NaN       7.0          NaN
TOI           NaN         101.0    16525.0    4597.0    3250.0       5544.0


C_APPP_RES UNVERIFIED_NON_LOGGED_IN    URL
A_K
AM                             47.0    NaN
BM                            509.0    NaN
ES                             15.0    1.0
ET                           6401.0  306.0
ETBLOG                          NaN    NaN
ETPRIME                        31.0    3.0
FEMINA                          NaN    5.0
GTech                         145.0    2.0
INDIATIMES                      NaN   63.0
MALAY                           NaN    1.0
MM                            868.0    1.0
MTO                           338.0    5.0
NBTO                          176.0   29.0
NBTRB                           NaN    NaN
PM                             54.0    NaN
TELGU                           6.0    1.0
TFOOD                          21.0    7.0
TIMESB                          NaN    2.0
TJC                            66.0    NaN
TOI                          7297.0  271.0

In [11]:
import numpy as np
df_new_3 = df_new_2.replace(np.nan, 0)

In [12]:
df_new_3

            Count                                                           \
C_APPP_RES      1 ARTICLE_PASTED BATCH_PROCESS_PAST DUPLICATE ED_OFFENSIVE
A_K
AM            0.0            0.0                0.0       1.0          0.0
BM            0.0            0.0               19.0      18.0          0.0
ES            0.0            1.0                5.0       6.0          0.0
ET            0.0            0.0             1249.0    3100.0          0.0
ETBLOG        0.0            0.0                5.0       0.0          0.0
ETPRIME       0.0            0.0                0.0       0.0          0.0
FEMINA        0.0            0.0                4.0       0.0          0.0
GTech         0.0            0.0                3.0       3.0          0.0
INDIATIMES    0.0            0.0               32.0      26.0          0.0
MALAY         0.0            0.0               21.0       0.0          0.0
MM            0.0            0.0                4.0      32.0          0.0
MTO          21.0            4.0               53.0      82.0          0.0
NBTO        181.0            0.0               61.0      84.0          6.0
NBTRB         0.0            0.0                2.0      28.0          0.0
PM            0.0            0.0                0.0       1.0          0.0
TELGU         0.0            0.0               21.0       1.0          0.0
TFOOD         0.0            0.0                0.0       2.0          0.0
TIMESB        0.0            0.0               12.0      44.0          0.0
TJC           0.0            0.0                0.0       0.0          0.0
TOI         884.0            0.0             3291.0    7127.0          0.0

                                                                             \
C_APPP_RES  EMAIL LARGE_COMMENT ML_PROCESS OFFENSIVE PHONE_NUM PURGE_ACTION
A_K
AM            0.0           0.0        0.0       0.0      17.0          0.0
BM            0.0           1.0        0.0       0.0      32.0          1.0
ES            0.0           0.0        0.0       0.0       6.0         19.0
ET          154.0          22.0        0.0       0.0    2069.0        948.0
ETBLOG        3.0           5.0        0.0       0.0     187.0          0.0
ETPRIME       0.0           0.0        0.0       0.0       1.0          0.0
FEMINA        0.0           0.0        0.0       0.0      18.0          0.0
GTech         3.0           0.0        0.0       0.0      51.0          6.0
INDIATIMES    2.0           0.0        0.0       0.0      26.0          0.0
MALAY         0.0           0.0        0.0       0.0       6.0          0.0
MM            0.0           2.0        0.0      10.0      27.0          8.0
MTO           0.0           9.0        0.0       6.0       7.0         10.0
NBTO          0.0          36.0      216.0       3.0      34.0          0.0
NBTRB         1.0           0.0        0.0       0.0       2.0          0.0
PM            0.0           1.0        0.0       0.0       6.0          1.0
TELGU         3.0           0.0        0.0       0.0      21.0          0.0
TFOOD         0.0           0.0        0.0       0.0       1.0          0.0
TIMESB        1.0           5.0        0.0       4.0      54.0          5.0
TJC           0.0           0.0        0.0       0.0       7.0          0.0
TOI           0.0         101.0    16525.0    4597.0    3250.0       5544.0


C_APPP_RES UNVERIFIED_NON_LOGGED_IN    URL
A_K
AM                             47.0    0.0
BM                            509.0    0.0
ES                             15.0    1.0
ET                           6401.0  306.0
ETBLOG                          0.0    0.0
ETPRIME                        31.0    3.0
FEMINA                          0.0    5.0
GTech                         145.0    2.0
INDIATIMES                      0.0   63.0
MALAY                           0.0    1.0
MM                            868.0    1.0
MTO                           338.0    5.0
NBTO                          176.0   29.0
NBTRB                           0.0    0.0
PM                             54.0    0.0
TELGU                           6.0    1.0
TFOOD                          21.0    7.0
TIMESB                          0.0    2.0
TJC                            66.0    0.0
TOI                          7297.0  271.0

In [14]:
df_new_3.to_csv('/Users/yash.dalmia/Downloads/jan_2021_rejected_count_formatted_jupyter.csv')